# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signinsheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='students_present',
            field=models.ManyToManyField(to='signinsheet.Student'),
        ),
    ]
