# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='session',
            name='students_present',
            field=models.ManyToManyField(blank=True, to='attendance.Student'),
        ),
    ]
